name: Perl and Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version: [ "5.32", "5.34", "5.36" ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}

    - name: Install Perl Dependencies
      run: |
        cpanm --quiet --installdeps .

    - name: Install Perl::Tidy and Perl::Critic
      run: |
        cpanm Perl::Tidy Perl::Critic

    - name: Run Perl::Tidy
      run: |
        find src -name "*.pl" -o -name "*.pm" | xargs perltidy -b -bext='.bak'
        find test -name "*.pl" | xargs perltidy -b -bext='.bak'

    - name: Run Perl::Critic
      run: |
        find src -name "*.pl" -o -name "*.pm" | xargs perlcritic
        find test -name "*.pl" | xargs perlcritic

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy

    - name: Run mypy
      run: |
        mypy src/bin/*.py

    - name: Run Perl Tests
      run: |
        prove -lr test/
      
    - name: Run Additional Test Scripts
      run: |
        bash test/runtest.sh
