version: '4.0'

services:
  web:
    image: nginx:1.21.6
    version: '4.0'
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  db:
    image: postgres:14.2
    container_name: db_server
    environment:
      POSTGRES_DB: changeddbname2ndtime
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changing2ndtime
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dbnet

volumes:
  db_data:
    driver: local
    driver_opts:
      o: "uid=1000,gid=1000"

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/25
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/25
